name: ht
description: a shell command that answers your questions about shell commands.
version: 1.0.0
homepage: https://github.com/catallo/ht/
environment:
  sdk: '>=2.18.3 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  compute: ^1.0.2
  http: ^1.1.0
