name: ht
description: an assistant that answers your questions about shell commands.
version: 1.0.0
# homepage: https://github.com/catallo/ht/
environment:
  sdk: '>=2.18.3 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dart_openai: ^4.0.0
