name: Dart Build

on: [push]

jobs:
  compile:
    name: Compile Dart Project
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            binary-name: ht_linux_amd64
          - runs-on: macos-latest
            binary-name: ht_macos_amd64
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: mkdir out
      - run: dart compile exe bin/ht.dart -o out/${{ matrix.binary-name }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.binary-name }}
          path: out/${{ matrix.binary-name }}
