name: Dart Build

on: [push]

jobs:
  compile:
    name: Compile Dart Project
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            archive-suffix: linux64
          - runs-on: macos-latest
            archive-suffix: MacOS_ARM64
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get

      # Extract version
      - name: Extract version
        id: get_version
        run: |
         VERSION=$(awk -F '"' '/const version =/ {print $2}' lib/globals.dart)
         echo "VERSION=$VERSION" >> $GITHUB_ENV
         echo "::set-output name=version::$VERSION"
         VERSION_FORMATTED=$(echo $VERSION | sed 's/\./-/g')
         echo "VERSION_FORMATTED=$VERSION_FORMATTED" >> $GITHUB_ENV

      # Debug: Print extracted version
      - name: Print version
        run: echo "Extracted version is $VERSION"

      - run: mkdir out
      - run: dart compile exe bin/ht.dart -o out/ht
 
      # Set executable bit
      - run: chmod +x out/ht

      # Zip the executable to preserve file permissions
      - run: |
          cd out
          zip -j ht_${{ env.VERSION_FORMATTED }}_${{ matrix.archive-suffix }}.zip ht

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"


      - uses: actions/upload-artifact@v2
        with:
          name: ht_${{ env.VERSION_FORMATTED }}_${{ matrix.archive-suffix }}.zip
          path: out/ht_${{ env.VERSION_FORMATTED }}_${{ matrix.archive-suffix }}.zip
